[package]
name = "individual_project_3"
version = "0.1.0"
edition = "2021"


[dependencies]
ndarray = "0.15"
ndarray-stats = "0.5.0"
thiserror = "1.0"
linfa = "0.6.1"
linfa-logistic = "0.6.1"
linfa-datasets = { version = "0.6.1", features = ["winequality"] }

